In [1]:
##Creates a matrix of NumRows rows by NumCols columns
##Each entry of the matrix is a one or a zero based on a vector "dataRows" 
# the vector "dataRows" has NumRows components and specifyies, for each row, which columns should be 1
import numpy as np
import pandas as pd
def IndicatorMatrix(NumRows,NumCols,dataRows):
    matrix = np.zeros((NumRows,NumCols),dtype=int)
    for i in range(0,4):
        matrix[i,dataRows[i]-1]=1
    return matrix
r=4
c=3
data=np.array([1,1,2,3])#One element for each row. It says which column will be one
a=IndicatorMatrix(r,c,data)

In [2]:
print(a)

[[1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
